In [94]:
#  A Linear regression Model using PyTorch

import torch
import torch.optim as optim
import numpy as np
import torch.nn as nn

# Initialize parameters
true_w = 2
true_b = 1
N = 100 # Start with 100 data points
#  Generate random data and split it 80/20
X = np.random.rand(N, 1) 
y = true_w * X + true_b
split_data = int(0.8 * len(X))
x_train, y_train = X[:split_data], y[:split_data]
x_test, y_test = X[split_data:], y[split_data:]

#  Set GPU device
device = "cuda" if torch.cuda.is_available() else "cpu"
# Convert to tensors
x_train_tensor = torch.from_numpy(x_train).float().to(device)
y_train_tensor = torch.from_numpy(y_train).float().to(device)
x_test_tensor = torch.from_numpy(x_test).float().to(device)
y_train_tensor = torch.from_numpy(y_train).float().to(device)
# Set a learning rate
learn_rate = 0.1

# Use PyTorch Class to represent our model
# Which inherits from the nn.Module Class
class LinearRegression(nn.Module):
    def __init__(self):
        super().__init__()
        # Wrap w & b with nn.Parameter
        self.w = nn.Parameter(torch.randn(1, requires_grad=True, \
        dtype=torch.float))
        self.b = nn.Parameter(torch.randn(1, requires_grad=True,  \
        dtype=torch.float))

        # Forward function that defines predictions
    def forward(self, x):
          return self.w * x_train_tensor + self.b

torch.manual_seed(42)
model = LinearRegression().to(device)
print(f"\n{list(model.parameters())}")            
                                          
# print(f"Initial w & b:\n {w}, {b}")
# Make prediction - forward pass
yhat = model(x_train_tensor)
# Compute the error and sebsequntly the loss
# We use a MSE loss function
loss_func = nn.MSELoss(reduction='mean')
# error = yhat - y_train_tensor
# loss = (error ** 2).mean()
# print(f"Initial loss is: \n {loss}")
# # Compute gradients for parameters b & w
# loss.backward()
# Compute gradient
optimizer = optim.SGD([w, b], lr=learn_rate)
print(f"\nState dict: \n{optimizer.state_dict()}")

# Set the number of epochs
num_epochs = 1000
# Build training loop for 1000 epochs
for epoch in range(num_epochs):
    # Step 1 - Compute the model's prediction
    yhat = w * x_train_tensor + b
    
    # Step 2 - Compute the loss
    loss = loss_func(yhat, y_train_tensor)
    # error = (yhat - y_train_tensor)
    # loss =(error ** 2).mean()
    # Step 3 Compute gradients for b & w
    loss.backward()
    # Step 4 - Optimize the parameters
    optimizer.step()
    # Zero out the gradients as pytorch acumulates them by default.
    optimizer.zero_grad()

print(f"\nFinal values for w & b:\n {w}, {b}")


[Parameter containing:
tensor([0.3367], device='cuda:0', requires_grad=True), Parameter containing:
tensor([0.1288], device='cuda:0', requires_grad=True)]

State dict: 
{'state': {}, 'param_groups': [{'lr': 0.1, 'momentum': 0, 'dampening': 0, 'weight_decay': 0, 'nesterov': False, 'maximize': False, 'foreach': None, 'differentiable': False, 'fused': None, 'params': [0, 1]}]}

Final values for w & b:
 tensor([2.0000], device='cuda:0', requires_grad=True), tensor([1.0000], device='cuda:0', requires_grad=True)
